In [3]:
# 1a
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])




Reversed: [5 4 6 3 2 1]


In [4]:
# 1b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.ravel())
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [5]:
#1c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1, arr2)


True

In [6]:
# 1d
x = np.array([1,2,3,4,5,1,2,1,1,1])
from collections import Counter
most_frequent = Counter(x).most_common(1)[0][0]
print("Most frequent:", most_frequent)
print("Indices:", np.where(x == most_frequent))

Most frequent: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [7]:
# 1e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

totalsum = np.sum(gfg)

rowsum = np.sum(gfg, axis=1)

colsum = np.sum(gfg, axis=0)

print(totalsum)
print(rowsum)
print(colsum)


45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [8]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
from collections import Counter
most_common = Counter(y).most_common(1)[0][0]
print("Most frequent:", most_common)
print("Indices:", np.where(y == most_common))

Most frequent: 1
Indices: (array([0, 1, 2]),)


In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner = np.inner(x, y)

# Outer product (flattened)
outer = np.outer(x, y)

# Cartesian product
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner)
print(outer)
print(cartesian)


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [17]:
# i.
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print(np.dot(p1, q1))
print(np.cov(p1.transpose(), q1.transpose()))

# ii.
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x, y))
print()
print(np.outer(x, y))
print()
print(np.array(np.meshgrid(x.flatten(), y.flatten())).transpose().reshape(-1, 2))


[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
[[17 52]
 [13 62]]

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
#  Question
 gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [11]:
# 2
array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Absolute
abs_array = np.abs(array)

# ii. Percentiles
flat = array.flatten()
percentiles = np.percentile(flat, [25, 50, 75])
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print(abs_array)
print(percentiles)
print(col_percentiles)
print(row_percentiles)

# iii. Stats
mean = np.mean(flat)
median = np.median(flat)
std = np.std(flat)

col_mean = np.mean(array, axis=0)
row_mean = np.mean(array, axis=1)

print(mean, median, std)
print(col_mean)
print(row_mean)


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]


In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print(floor_vals)
print(ceil_vals)
print(trunc_vals)
print(round_vals)


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [13]:
# Q3
arr = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(arr))
print("Top 5:", np.sort(arr)[-5:])

[ 10  16  16  52  54  62 453]
Top 5: [ 16  52  54  62 453]


In [19]:
# Q4

import cv2
def img_to_array(path):
    img = cv2.imread(path)
    if len(img.shape) == 2:
        np.savetxt("grayscaleimage.txt", img, fmt='%d')
    else:
        for i in range(3):
            np.savetxt(f"channel_{i}.txt", img[:,:,i], fmt='%d')
path = '/Users/kenpreet/Desktop/Screenshot 2025-08-05 at 7.24.28 AM.png'\

img_to_array(path)

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
#grey

r = np.loadtxt("channel_0.txt", dtype=int)
g = np.loadtxt("channel_1.txt", dtype=int)
b = np.loadtxt("channel_2.txt", dtype=int)

r, g, b
